### ISSUE TITLE
Archive this project?

### ISSUE THREAD

**Issue by stinodego** [pola-rs/valves#18]
@koaning this project has not been updated in a while.

There are now other solutions available, like Polars plugins and projects like [polars-ds](https://pypi.org/project/polars-ds/).

Do you have any plans with this project? If not, I propose we archive it.

**Comment by koaning** [comment]
Oh totally, by all means. 

It was a fun idea, but it's certainly retired now.

**Comment by stinodego** [comment]
All right, will archive it then. If you want to have this in your personal archive as well, I'd recommend forking it. Not sure we want to keep this around within the Polars organization indefinitely.
